nodeLinker: pnp

packageExtensions:
  '@octokit/request@*':
    dependencies:
      'encoding': '*'
  'axios@*':
    dependencies:
      'debug': '*'
  'debug@*':
    dependencies:
      'supports-color': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
